### ISSUE TITLE
peerDependencies

### ISSUE THREAD

**Issue by ghost** [samme/phaser-plugin-debug-draw#9]
Hi Samme, could you remove the peer-deps, so we can install it without --force and newer Versions of Phaser.
Thank you for the plugins, very helpful for debugging!

**Comment by samme** [comment]
I assume you're using Phaser v3.60 beta? 

If it works with `--force`, I would do that and ignore the warnings. I don't want to remove the peer dependency because the plugin does require Phaser v3.53 or later. Maybe there's a way to include the beta also.

**Comment by luchillo17** [comment]
The peer dep version is `^3.53.0` ~~which should allow any minor version, maybe it was updated later~~?
Ah, the semver ranges don't match suffixed versions like `3.6.0-beta.x`, ok I learned something new, still, if you're delving into beta versions you should expect the need to use `--force` or overrides...

**Comment by samme** [comment]
I can't figure out how to include both Phaser stable and pre-release versions, so I think I'll advise people to use `--force` for now.

**Comment by luchillo17** [comment]
Seems like a pain since you would have to add a tag for each patch-level version with a pre-release:
https://stackoverflow.com/a/68774204/4325989
